spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cryptomanager2?useSSL=false&allowPublicKeyRetrieval=true
    username: cryptomanager2
    password: cryptomanager2
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
logging:
  level:
    root: WARN
    nl.kolkos.cryptomanager: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
server:
#  port: 8443
#  ssl:
#    enabled: true
#    key-store: classpath:keystore.jks
#    key-store-password: photogallery
#    key-store-type: JKS
#    key-alias: tomcatssl
#    key-password: photogallery
#    key-store-provider: SUN
  error:
    include-stacktrace: always